"""build -- render docs/config.js and assemble docs/ from site/ + schemas/.

This repo's product is a static page, not a data pipeline, so this is the
only step (PRIMER.md A2): main.py exists for the same reason it exists in
every family repo (one entry point, --list/--dry-run/--strict), not
because there are several steps here.

Offline (PRIMER.md A3 / A2): nothing here touches the network. The live
schema fetch happens client-side, in the browser, when someone opens the
page -- never during this build.

Everything under docs/ is generated by this step. None of it is a source;
`site/` and `schemas/` are. Two docs/ paths are byte-identical copies
(index.html, app.css, app.js) rather than templated, because they contain
no per-build variable -- forcing static markup through Jinja2 for zero
substitutions would be indirection with no payoff. docs/config.js is the
one file with real substitutions (RELEASE, the schema URLs), so it is the
one that is actually templated -- see py/templates/config.js.j2.

`--strict` additionally lints site/index.html: every `<script src=` /
`import ... from` URL that points at a CDN must carry an exact version
number matching py/md_generator_utils.py's *_VERSION constants. This is
the guard against the failure mode PRIMER.md A3 warns about generally
("a guard that gets lost in the copy is the most dangerous form of
reuse") applied to this repo's actual risk: someone loosening a CDN pin
to `@latest` in a future edit without noticing, and the page silently
starts loading a different major version of ajv/js-yaml/jszip/leaflet.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from jinja2 import Environment, FileSystemLoader

from py.md_generator_utils import (
    AJV_2020_ESM_CDN,
    AJV_DRAFT07_ESM_CDN,
    CITATION_CFF_SCHEMA_DOCS_PATH,
    CITATION_CFF_SCHEMA_SRC,
    CLASSIFICATION_RULES_DOCS_PATH,
    CLASSIFICATION_RULES_SRC,
    DOCS,
    JS_YAML_VERSION,
    JSZIP_VERSION,
    LEAFLET_VERSION,
    MD_CFF_SCHEMA_URL,
    RELEASE,
    REPO_ROOT,
    SITE,
    copy_verbatim,
    ensure_dirs,
    write_text,
)

TEMPLATES = REPO_ROOT / "py" / "templates"

# Maps a version constant to every "@<version>" occurrence site/index.html
# must contain for that library, for the --strict pin-lint. Only the three
# classic-<script> globals live in site/index.html by hand; ajv is never
# hand-authored there -- it only ever appears via AJV_VERSION -> the CDN
# URL constants above -> docs/config.js, all generated from this one
# Python constant, so there is no separate place for its pin to drift
# from (nothing to lint). A library that stops appearing here (or a
# version that stops matching) means site/index.html and this module's
# constants have drifted apart.
REQUIRED_PINS = {
    "js-yaml": JS_YAML_VERSION,
    "jszip": JSZIP_VERSION,
    "leaflet": LEAFLET_VERSION,
}
_UNPINNED_RE = re.compile(r"(js-yaml|jszip|leaflet)@(latest|next|\^|~)", re.IGNORECASE)


def _lint_pins(html: str) -> list[str]:
    problems: list[str] = []
    floating = _UNPINNED_RE.findall(html)
    if floating:
        problems.append(f"floating CDN version reference(s) found: {floating}")
    for lib, version in REQUIRED_PINS.items():
        if f"{lib}@{version}" not in html:
            problems.append(f"expected pin '{lib}@{version}' not found in site/index.html")
    return problems


def run(args: argparse.Namespace) -> tuple[bool, str]:
    ensure_dirs()

    env = Environment(loader=FileSystemLoader(str(TEMPLATES)), keep_trailing_newline=True)
    rendered = env.get_template("config.js.j2").render(
        release=RELEASE,
        md_cff_schema_url=MD_CFF_SCHEMA_URL,
        citation_cff_schema_path=CITATION_CFF_SCHEMA_DOCS_PATH,
        classification_rules_path=CLASSIFICATION_RULES_DOCS_PATH,
        ajv_2020_esm_url=AJV_2020_ESM_CDN,
        ajv_draft07_esm_url=AJV_DRAFT07_ESM_CDN,
    )
    write_text(rendered, DOCS / "config.js")

    for name in ("index.html", "app.css", "app.js"):
        src = SITE / name
        if not src.exists():
            return False, f"{src} not found -- site/ is a source directory, it must be committed"
        copy_verbatim(src, DOCS / name)

    copy_verbatim(CITATION_CFF_SCHEMA_SRC, DOCS / CITATION_CFF_SCHEMA_DOCS_PATH)
    copy_verbatim(CLASSIFICATION_RULES_SRC, DOCS / CLASSIFICATION_RULES_DOCS_PATH)

    written = ["config.js", "index.html", "app.css", "app.js",
               CITATION_CFF_SCHEMA_DOCS_PATH, CLASSIFICATION_RULES_DOCS_PATH]
    message = f"wrote docs/{{{', '.join(written)}}}"

    if getattr(args, "strict", False):
        html = (SITE / "index.html").read_text(encoding="utf-8")
        problems = _lint_pins(html)
        if problems:
            return False, "pin-lint failed: " + "; ".join(problems)
        message += " (pin-lint OK)"

    return True, message


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true", help="Also lint site/index.html for floating/missing CDN version pins.")
    ok, message = run(ap.parse_args())
    print(f"[build] {message}")
    raise SystemExit(0 if ok else 1)
